sonar.projectKey=Azer-khadhraoui_ATB-Credit-Platform
sonar.organization=azer-khadhraoui

sonar.sources=backend/src/main,frontend/src/app,ml-service/app
sonar.tests=backend/src/test,frontend/src/app
sonar.test.inclusions=**/*.spec.ts,**/*Tests.java,**/*Test.java

sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/target/**,ml-service/notebooks/**,ml-service/data/**,ml-service/models/**

sonar.java.binaries=backend/target/classes
