spring.application.name=backend
server.port=8081

spring.mongodb.uri=mongodb://localhost:27017/atb_credit_platform
spring.data.mongodb.auto-index-creation=true

logging.level.tn.atb.backend=DEBUG
logging.level.org.springframework.data.mongodb=INFO